name: Ubuntu Build
on:
  push:
    branches:
      - master
      - fix/workflow-builds
  pull_request:
    branches:
      - master

jobs:
  ubuntu_build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install ccache
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache

      - name: Cache ccache directory
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.c', '**/*.h', '**/*.cpp', 'meson.build', 'meson_options.txt') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Setup ccache
        run: |
          echo "/usr/lib/ccache" >> $GITHUB_PATH
          ccache --set-config=max_size='1.0G'
          ccache --zero-stats

      - name: Install Dependencies
        run: |
          sudo apt-get install -y meson libcanberra-dev libdbus-glib-1-dev libglib2.0-dev libgtk2.0-dev libluajit-5.1-dev libpci-dev libperl-dev libssl-dev python3-dev python3-cffi mono-devel desktop-file-utils
          python3 --version

      - name: Configure
        run: meson build -Dtext-frontend=true -Dtheme-manager=true -Dauto_features=enabled

      - name: Build
        run: ninja -C build

      - name: Test
        run: ninja -C build test

      - name: Create tar.gz artifact
        run: |
          mkdir -p hexchat-ubuntu-build
          DESTDIR=hexchat-ubuntu-build ninja -C build install
          tar -czf hexchat-2.16.3-ubuntu.tar.gz -C hexchat-ubuntu-build .

      - name: Show ccache statistics
        run: ccache --show-stats

      - name: Install
        run: sudo ninja -C build install

      - uses: actions/upload-artifact@v4
        with:
          name: Ubuntu Tarball
          path: hexchat-2.16.3-ubuntu.tar.gz
